language: node_js
node_js:
  - "6"
install:
  - npm install -g mocha
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_DIR=server/

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

script:
  - cd $TEST_DIR
  - npm install
  - npm test
notifications:
  email: false
